// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/apiarian/ipfs-pinbase/cmd/ipfs-pinbase/design
// --out=$(GOPATH)/src/github.com/apiarian/ipfs-pinbase/cmd/ipfs-pinbase
// --version=v1.1.0-dirty
//
// API "pinbase": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

// partyPayload user type.
type partyPayload struct {
	// A helpful description of the party
	Description *string `form:"description,omitempty" json:"description,omitempty" xml:"description,omitempty"`
	// The hash of the object describing the party
	Hash *string `form:"hash,omitempty" json:"hash,omitempty" xml:"hash,omitempty"`
}

// Publicize creates PartyPayload from partyPayload
func (ut *partyPayload) Publicize() *PartyPayload {
	var pub PartyPayload
	if ut.Description != nil {
		pub.Description = ut.Description
	}
	if ut.Hash != nil {
		pub.Hash = ut.Hash
	}
	return &pub
}

// PartyPayload user type.
type PartyPayload struct {
	// A helpful description of the party
	Description *string `form:"description,omitempty" json:"description,omitempty" xml:"description,omitempty"`
	// The hash of the object describing the party
	Hash *string `form:"hash,omitempty" json:"hash,omitempty" xml:"hash,omitempty"`
}
