// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/apiarian/ipfs-pinbase/design
// --out=$(GOPATH)/src/github.com/apiarian/ipfs-pinbase
// --version=v1.1.0-dirty
//
// API "pinbase": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"fmt"
	"strings"
)

// NodeHref returns the resource href.
func NodeHref(nodeHash interface{}) string {
	paramnodeHash := strings.TrimLeftFunc(fmt.Sprintf("%v", nodeHash), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/nodes/%v", paramnodeHash)
}
