basePath: /api
consumes:
- application/json
definitions:
  CreatePartyPayload:
    example:
      description: Nostrum architecto repellendus molestiae et.
      hash: Rerum accusamus voluptates atque.
    properties:
      description:
        description: A helpful description of the party
        example: Nostrum architecto repellendus molestiae et.
        type: string
      hash:
        description: The hash of the object describing the party
        example: Rerum accusamus voluptates atque.
        type: string
    required:
    - hash
    - description
    title: CreatePartyPayload
    type: object
  PinbaseParty:
    description: A Pinbase Party (default view)
    example:
      description: Ut provident ratione doloribus id consequuntur.
      hash: Reiciendis necessitatibus dolor magnam voluptates.
    properties:
      description:
        description: A helpful description of the party
        example: Ut provident ratione doloribus id consequuntur.
        type: string
      hash:
        description: The hash of the object describing the party
        example: Reiciendis necessitatibus dolor magnam voluptates.
        type: string
    required:
    - hash
    - description
    title: 'Mediatype identifier: application/vnd.pinbase.party+json; view=default'
    type: object
  PinbasePartyCollection:
    description: PinbasePartyCollection is the media type for an array of PinbaseParty
      (default view)
    example:
    - description: Ut provident ratione doloribus id consequuntur.
      hash: Reiciendis necessitatibus dolor magnam voluptates.
    items:
      $ref: '#/definitions/PinbaseParty'
    title: 'Mediatype identifier: application/vnd.pinbase.party+json; type=collection;
      view=default'
    type: array
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
  party-payload:
    example:
      description: Nostrum architecto repellendus molestiae et.
      hash: Rerum accusamus voluptates atque.
    properties:
      description:
        description: A helpful description of the party
        example: Nostrum architecto repellendus molestiae et.
        type: string
      hash:
        description: The hash of the object describing the party
        example: Rerum accusamus voluptates atque.
        type: string
    title: party-payload
    type: object
host: localhost:3000
info:
  contact:
    email: al@megamicron.net
    name: Aleksandr Pasechnik
    url: https://megamicron.net
  description: The IPFS-pinbase API
  license:
    name: MIT
  title: pinbase
  version: "0.1"
paths:
  /parties:
    get:
      description: List the parties available in this pinbase
      operationId: party#list
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PinbasePartyCollection'
      schemes:
      - http
      summary: list party
      tags:
      - party
    post:
      description: Create a party
      operationId: party#create
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreatePartyPayload'
      responses:
        "201":
          description: Resource created
          headers:
            Location:
              description: href to the created resource
              pattern: /parties/.+
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: create party
      tags:
      - party
  /parties/{partyHash}:
    delete:
      description: Delete a party
      operationId: party#delete
      parameters:
      - description: Party Hash
        in: path
        name: partyHash
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: delete party
      tags:
      - party
    get:
      description: Get the party by hash
      operationId: party#show
      parameters:
      - description: Party Hash
        in: path
        name: partyHash
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PinbaseParty'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show party
      tags:
      - party
    patch:
      description: Change a party's description
      operationId: party#update
      parameters:
      - description: Party Hash
        in: path
        name: partyHash
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/party-payload'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PinbaseParty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: update party
      tags:
      - party
produces:
- application/json
responses:
  NoContent:
    description: No Content
  NotFound:
    description: Not Found
schemes:
- http
swagger: "2.0"
